Add void to functions in C missing parameters to fix -Wstrict-prototypes warnings.
This warning became more strict in the updated clang compiler.

The error message that this change fixes is:

```
error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
```
PiperOrigin-RevId: 472545870