Update RVM to 2.3.0 as it's failing to update (#780)
* Update RVM to 2.3.0 as it's failing to update

https://travis-ci.org/google/EarlGrey/jobs/471151306:
```
Updating rubygems-update
ERROR:  Error installing rubygems-update:
	rubygems-update requires Ruby version >= 2.3.0.
ERROR:  While executing gem ... (NoMethodError)
    undefined method `version' for nil:NilClass
The command "gem update --system" failed and exited with 1 during .
```

* Forgot to update it everywhere.

Also using the most latest stable version 2.5.3

* remove --no-rdoc option as it's unavailable

```
$ gem install xcpretty --no-rdoc --no-ri --no-document --quiet
ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --no-rdoc
The command "gem install xcpretty --no-rdoc --no-ri --no-document --quiet" failed and exited with 1 during .
```

* Remove --no-ri option