Update RVM to 2.3.0 as it's failing to update
https://travis-ci.org/google/EarlGrey/jobs/471151306:
```
Updating rubygems-update
ERROR:  Error installing rubygems-update:
	rubygems-update requires Ruby version >= 2.3.0.
ERROR:  While executing gem ... (NoMethodError)
    undefined method `version' for nil:NilClass
The command "gem update --system" failed and exited with 1 during .
```